// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleBookingSystem.DataAccess;

namespace SimpleBookingSystem.Migrations
{
    [DbContext(typeof(SimpleBookingSystemDbContext))]
    [Migration("20230103082727_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("SimpleBookingSystem.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("booking");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedQuantity = 2,
                            DateFrom = new DateTime(2023, 1, 3, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2023, 1, 3, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            ResourceId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookedQuantity = 4,
                            DateFrom = new DateTime(2023, 1, 3, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2023, 1, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ResourceId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookedQuantity = 6,
                            DateFrom = new DateTime(2023, 1, 3, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2023, 1, 3, 15, 15, 0, 0, DateTimeKind.Unspecified),
                            ResourceId = 3
                        });
                });

            modelBuilder.Entity("SimpleBookingSystem.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("resource");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Resource1",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            Name = "Resource2",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 3,
                            Name = "Resource3",
                            Quantity = 15
                        });
                });

            modelBuilder.Entity("SimpleBookingSystem.Entities.Booking", b =>
                {
                    b.HasOne("SimpleBookingSystem.Entities.Resource", "Resource")
                        .WithMany("Bookings")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
